### ISSUE TITLE
Public opinion on PR template

### ISSUE THREAD

**Issue by avats-dev** [BitByte-TPC/first-bit#5]
I'm thinking about adding a PR template along with issue templates. As this repo is focused on helping newcomers, I've also mentioned how this could help them.

#### Issue template (possible options):
- report bugs (well there always could be something crawling)
- feature request (it is what is says)
- newcomer (for newcomers, and people should open this issue first and then open a PR linking back to this issue)

#### PR template (there is generally just one):
- Along with forking, cloning and adding commits and then opening a PR, people would know describing a PR and linking back to a issue.
- For newcomers this PR should link back to the **newcomer** issue that they've opened.

#### Advantages:
- people with get familiar with reporting issues and describing PRs.
- people also get a hang of markdown, i learned like this :smile: .
- we could give an option to people while opening **newcomer** issue to opt for a mentor if they're still unsure of what's happening and need help. This will help us in identifying and help them through this. 

Drop suggestions and edits, constructive criticism can only help us grow. :rocket:

**Comment by garg3133** [comment]
@Samy-33 @Janglee123

**Comment by Samy-33** [comment]
Sounds good to me. Go on @avats-dev

**Comment by Janglee123** [comment]
I don't find the point for newcomers issue. It will make the process a little bit more complex. It supposed to be simple or otherwise, you have to write a guide about it too. IMO keep the process simple to fork, clone, change, commit, push and pr. You see that's already a lot of things to learn in one go. 

As you might not aware we are working on getting started project where we put guides for each subject. You can add a guide for markdown, GitHub issues and etc. :)

**Comment by avats-dev** [comment]
@Janglee123 so I'll add a PR template for now, and issue templates for bug report and feature request. We can tackle md and other things later.
